#!/usr/bin/env python3
"""Generate Globe's compact latitude/longitude wireframe paths."""
import math
import sys


def point(lon, lat):
    lon, lat = math.radians(lon), math.radians(lat)
    return (round(100 * math.cos(lat) * math.sin(lon)),
            round(100 * math.sin(lat)),
            round(100 * math.cos(lat) * math.cos(lon)))


def write_path(stream, label, points):
    stream.write("gl_%s: db %s\n" %
                 (label, ",".join(str(v) for p in points for v in p)))


with open(sys.argv[1], "w", encoding="ascii") as out:
    out.write("; Generated by tools/globe_graticule.py; do not edit.\n\n")
    paths = []
    for label, latitude in (("equator", 0), ("tropic_n", 23),
                            ("tropic_s", -23), ("polar_n", 66),
                            ("polar_s", -66)):
        paths.append((label, [point(lon, latitude) for lon in range(0, 361, 15)]))
    # 24 meridians, spaced 15 degrees apart: the complete 360-degree globe.
    for longitude in range(0, 360, 15):
        paths.append(("meridian_%d" % longitude,
                      [point(longitude, lat) for lat in range(-90, 91, 15)]))
    for label, points in paths:
        write_path(out, label, points)
    out.write("\ngl_grid_shapes:\n")
    for label, points in paths:
        out.write("    dw gl_%s\n    db %d\n" % (label, len(points)))
    out.write("    dw 0\n    db 0\n")
