#!/usr/bin/env python3
"""Turn Figshare's Continent Polygons shapefiles into Globe's tiny Q7 model.

Source: Stephanie Shepherd, *Continent Polygons*, Figshare v3, CC BY 4.0,
https://doi.org/10.6084/m9.figshare.12555170.v3

Usage:
  python3 tools/globe_contours.py /path/to/extracted-shapefiles \
      apps/globe/globe_contours.inc
"""
import math
import os
import struct
import sys

CONTINENTS = [
    ("North America", "namerica", "CGREEN", 3),
    ("South America", "samerica", "CGREEN", 2),
    ("Europe", "europe", "CYELLOW", 2),
    ("Africa", "africa", "CBROWN", 4),
    ("Asia", "asia", "CYELLOW", 3),
    ("Australia", "australia", "CMAGENTA", 3),
    ("Oceania", "oceania", "CLBLUE", 3),
    # White disappears against the background; cyan is reserved for ocean.
    ("Antarctica", "antarctica", "CLBLUE", 1),
]


def rings(path):
    data = open(path, "rb").read()
    pos = 100
    out = []
    while pos + 8 <= len(data):
        _, words = struct.unpack(">2i", data[pos:pos + 8])
        end = pos + 8 + words * 2
        body = data[pos + 8:end]
        pos = end
        if len(body) < 44 or struct.unpack("<i", body[:4])[0] != 5:
            continue
        parts, points = struct.unpack("<2i", body[36:44])
        starts = struct.unpack("<%di" % parts, body[44:44 + 4 * parts])
        xy = struct.unpack("<%dd" % (points * 2), body[44 + 4 * parts:44 + 4 * parts + points * 16])
        coords = list(zip(xy[::2], xy[1::2]))
        for i, start in enumerate(starts):
            ring = coords[start:starts[i + 1] if i + 1 < parts else points]
            if len(ring) > 3:
                out.append(ring)
    return out


def area(points):
    return abs(sum(x1 * y2 - x2 * y1 for (x1, y1), (x2, y2) in zip(points, points[1:])))


def dist(point, first, last):
    x, y = point
    x1, y1 = first
    x2, y2 = last
    dx, dy = x2 - x1, y2 - y1
    if dx == dy == 0:
        return math.hypot(x - x1, y - y1)
    return abs(dy * x - dx * y + x2 * y1 - y2 * x1) / math.hypot(dx, dy)


def rdp(points, epsilon):
    if len(points) < 3:
        return points
    index, maximum = 0, 0.0
    for i in range(1, len(points) - 1):
        value = dist(points[i], points[0], points[-1])
        if value > maximum:
            index, maximum = i, value
    if maximum <= epsilon:
        return [points[0], points[-1]]
    return rdp(points[:index + 1], epsilon)[:-1] + rdp(points[index:], epsilon)


def simplify(ring, limit=15):
    pts = ring[:-1] if ring[0] == ring[-1] else ring[:]
    # Close at a vertex that is not the antimeridian seam, then simplify.
    closed = pts + [pts[0]]
    epsilon = 0.15
    simplified = rdp(closed, epsilon)
    while len(simplified) > limit + 1:
        epsilon *= 1.45
        simplified = rdp(closed, epsilon)
    return simplified


def q7(lon, lat):
    lon, lat = math.radians(lon), math.radians(lat)
    c = math.cos(lat)
    return (round(100 * c * math.sin(lon)), round(100 * math.sin(lat)),
            round(100 * c * math.cos(lon)))


def centre(ring):
    pts = ring[:-1] if ring[0] == ring[-1] else ring
    return (sum(p[0] for p in pts) / len(pts), sum(p[1] for p in pts) / len(pts))


def main(source, output):
    rows = []
    for filename, stem, colour, maximum in CONTINENTS:
        candidates = sorted(rings(os.path.join(source, filename + ".shp")), key=area, reverse=True)
        chosen = candidates[:maximum]
        # Japan is a small but unmistakable Asian island chain; preserve one
        # ring near its geographic centre even though it is not among Asia's
        # largest land polygons.
        if filename == "Asia":
            japan = min(candidates, key=lambda ring: (centre(ring)[0] - 138) ** 2 +
                                                       (centre(ring)[1] - 36) ** 2)
            if japan not in chosen:
                chosen.append(japan)
        for number, ring in enumerate(chosen):
            # Antarctica's long irregular coast is its most recognisable cue;
            # retain twice the normal vertex budget while other shapes stay tiny.
            limits = {
                "Antarctica": 30,
                "Asia": 24,
                "Europe": 20,
                "North America": 24,
            }
            limit = limits.get(filename, 15)
            points = [q7(lon, lat) for lon, lat in simplify(ring, limit)]
            if len(points) < 3:
                continue
            label = "%s_%d" % (stem, number)
            rows.append((label, points, colour))
    with open(output, "w", encoding="ascii") as stream:
        stream.write("; Generated by tools/globe_contours.py; do not edit.\n")
        stream.write("; Source: Shepherd (2020), Continent Polygons v3, CC BY 4.0.\n\n")
        for label, points, _ in rows:
            stream.write("gl_%s: db %s\n" % (label, ",".join(str(n) for point in points for n in point)))
        stream.write("\ngl_shapes:\n")
        for label, points, colour in rows:
            stream.write("    dw gl_%s\n    db %d,%s\n" % (label, len(points), colour))
        stream.write("    dw 0\n    db 0,0\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
